/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Migrations__factory } from "./Migrations__factory";
export { SupplyChain__factory } from "./SupplyChain__factory";
