/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DIS"
      | "Distribute"
      | "MAN"
      | "Manufacturing"
      | "MedicineStock"
      | "Owner"
      | "RET"
      | "RMS"
      | "RMSsupply"
      | "Retail"
      | "addDistributor"
      | "addManufacturer"
      | "addMedicine"
      | "addRMS"
      | "addRetailer"
      | "disCtr"
      | "manCtr"
      | "medicineCtr"
      | "retCtr"
      | "rmsCtr"
      | "showStage"
      | "sold"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "DIS", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "Distribute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "MAN", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "Manufacturing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "MedicineStock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "Owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "RET", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "RMS", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "RMSsupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "Retail",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addDistributor",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addManufacturer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addMedicine",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addRMS",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addRetailer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(functionFragment: "disCtr", values?: undefined): string;
  encodeFunctionData(functionFragment: "manCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "medicineCtr",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "retCtr", values?: undefined): string;
  encodeFunctionData(functionFragment: "rmsCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "showStage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sold", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "DIS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Distribute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "Manufacturing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MedicineStock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RET", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RMS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RMSsupply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Retail", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMedicine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRMS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addRetailer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disCtr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "manCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "medicineCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "retCtr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rmsCtr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "showStage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sold", data: BytesLike): Result;
}

export interface SupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChain;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DIS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  Distribute: TypedContractMethod<
    [_medicineID: BigNumberish],
    [void],
    "nonpayable"
  >;

  MAN: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  Manufacturing: TypedContractMethod<
    [_medicineID: BigNumberish],
    [void],
    "nonpayable"
  >;

  MedicineStock: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        name: string;
        description: string;
        RMSid: bigint;
        MANid: bigint;
        DISid: bigint;
        RETid: bigint;
        stage: bigint;
      }
    ],
    "view"
  >;

  Owner: TypedContractMethod<[], [string], "view">;

  RET: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  RMS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  RMSsupply: TypedContractMethod<
    [_medicineID: BigNumberish],
    [void],
    "nonpayable"
  >;

  Retail: TypedContractMethod<
    [_medicineID: BigNumberish],
    [void],
    "nonpayable"
  >;

  addDistributor: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addManufacturer: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addMedicine: TypedContractMethod<
    [_name: string, _description: string],
    [void],
    "nonpayable"
  >;

  addRMS: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addRetailer: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  disCtr: TypedContractMethod<[], [bigint], "view">;

  manCtr: TypedContractMethod<[], [bigint], "view">;

  medicineCtr: TypedContractMethod<[], [bigint], "view">;

  retCtr: TypedContractMethod<[], [bigint], "view">;

  rmsCtr: TypedContractMethod<[], [bigint], "view">;

  showStage: TypedContractMethod<[_medicineID: BigNumberish], [string], "view">;

  sold: TypedContractMethod<[_medicineID: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DIS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "Distribute"
  ): TypedContractMethod<[_medicineID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "MAN"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "Manufacturing"
  ): TypedContractMethod<[_medicineID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "MedicineStock"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        name: string;
        description: string;
        RMSid: bigint;
        MANid: bigint;
        DISid: bigint;
        RETid: bigint;
        stage: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "Owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RET"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "RMS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "RMSsupply"
  ): TypedContractMethod<[_medicineID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "Retail"
  ): TypedContractMethod<[_medicineID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addDistributor"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addManufacturer"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addMedicine"
  ): TypedContractMethod<
    [_name: string, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addRMS"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addRetailer"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "manCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "medicineCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "retCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rmsCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "showStage"
  ): TypedContractMethod<[_medicineID: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "sold"
  ): TypedContractMethod<[_medicineID: BigNumberish], [void], "nonpayable">;

  filters: {};
}
